spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update